// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBai02bGu3Fqq24Vf-wld8eTKHccn-B8n4',
    appId: '1:1052056528612:web:ed1ccb59fab3da7ebfaef1',
    messagingSenderId: '1052056528612',
    projectId: 'disk-space-renting',
    authDomain: 'disk-space-renting.firebaseapp.com',
    storageBucket: 'disk-space-renting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPEa0wKWg1U0r-CL8qrsTAJXzeHu5AeEU',
    appId: '1:1052056528612:android:d45e6d0aa09114bdbfaef1',
    messagingSenderId: '1052056528612',
    projectId: 'disk-space-renting',
    storageBucket: 'disk-space-renting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpce7uXITQX4R4esGbq71ZeOlEXAAf3XU',
    appId: '1:1052056528612:ios:004ed78cceeab2cebfaef1',
    messagingSenderId: '1052056528612',
    projectId: 'disk-space-renting',
    storageBucket: 'disk-space-renting.appspot.com',
    iosClientId: '1052056528612-lal3pgetjbsvu1c38r88oe5p97fdf6g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.diskspacerenting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpce7uXITQX4R4esGbq71ZeOlEXAAf3XU',
    appId: '1:1052056528612:ios:004ed78cceeab2cebfaef1',
    messagingSenderId: '1052056528612',
    projectId: 'disk-space-renting',
    storageBucket: 'disk-space-renting.appspot.com',
    iosClientId: '1052056528612-lal3pgetjbsvu1c38r88oe5p97fdf6g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.diskspacerenting',
  );
}
